language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "10"
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
